[package]
name = "send_file_as_keys"
version = "0.1.0"
authors = ["Alejandro Benitez <maxneo4@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinputs = "0.0.5"
enigo = "0.0.14"

